name: Docker Image CI

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t metacode/infr .
    - name: Run the Docker image
      run: docker run --rm -i metacode/infr
